name: Deploy

on:
  push:
    branches: [main, dev]

permissions:
  id-token: write   
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug OIDC token claims
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | \
            jq -R 'split(".") | .[1] | @base64d | fromjson'
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::281257473315:role/github_oidc_role
          aws-region: us-west-2

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: environments/dev